private ["_canDeleteGroup","_group","_groups","_units"];

while {true} do {
	sleep 480 + (random 240);
	{deleteVehicle _x;} count allDead;
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "CraterLong");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "WeaponHolder");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "WeaponHolderSimulated");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "Ruins");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "GroundWeaponHolder");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "TimeBombCore");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "CraterLong_small");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "#destructioneffects");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "#particlesource");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "#slop");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "#mark");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "#track");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "#crater");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "#crateronvehicle");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "#explosion");
	sleep 3;
	{deleteVehicle _x;} count (allMissionObjects "#objectdestructed");
	sleep 3;
	{if (!isPlayer _x) then {_x enableFatigue FALSE;};} count allUnits;
	{if ((count units _x) == 0) then {deleteGroup _x;};} count allGroups;
};
